### PR TITLE
Improve settings ba1 to implement 1

### LINKED ISSUE #108: Settings Save Bug
**Describe the bug**
Currently it is not possible to save changes user settings, if the E-Mail field is empty.

**To Reproduce**
1. Login with a real user
2. Click on the user icon
3. Go to Settings
4. Clear the E-Mail field
5. Change any other field
6. Save changes
7. See that nothing changed

**Expected behavior**
The E-Mail field should be declared as a required field, so it is not possible to save the changes without an E-Mail entered.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by pinterid**
**Checklist:**

 

 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Documentation (non-breaking change which adds documentation)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently it is not possible to save changes user settings, if the E-Mail field is empty. #108 

**What is the new behavior (if this is a feature change)?**
- Now the E-Mail field is declared as required and the changes cannot be saved if its content is empty. #108 

**Other information**:
- Ref: 🐍

### CODE REVIEW

**Review by schettn — COMMENTED** [review]
Have you checked if there are other empty fields causing
the save problem too?

**Comment by pinterid** [comment]
> Have you checked if there are other empty fields causing
> the save problem too?

@schettn the mail field is the only required field (defined in the engine), although there was another bug on a user profile that if only the first name was entered and no last name, the name on a user profile was not displayed. But this issue was fixed in https://github.com/snek-at/front/pull/122.

**Review by kleberbaum — APPROVED** [review]
Should be ok to merge.

**Review by Aichnerc — APPROVED** [review]
LGTM

**Review by schettn — APPROVED** [review]
lgtm

**Pull request merged**
