### PR TITLE
Add homepage aa1 to implement 1

### PR DESCRIPTION
**Pull request by Aichnerc**
Two more sections have been added.

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Documentation (non-breaking change which adds documentation)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently the landing page lacks depth and showcases of our features. #70 

**What is the new behavior (if this is a feature change)?**
- The landing page has been updated and now showcases more of the benefits of joining SNEK. #70

### CODE REVIEW

**Review by schettn — APPROVED** [review]
LGTM

**Review by pinterid — APPROVED** [review]
Looks good.

**Review by schettn — CHANGES_REQUESTED** [review]
On my machine there is a issue with the date of the fancy week chart.
image
@Aichnerc have a look.

**Review by kleberbaum — APPROVED** [review]
Should be ok to merge.

**Review by simonprast — APPROVED** [review]
looks absolutely great

**Review by schettn — APPROVED** [review]
LGTM!

**Pull request merged**
